# TCL File Generated by Component Editor 7.2 on:
# Thu Mar 17 17:08:30 EDT 2011
# DO NOT MODIFY

set_source_file "de2_ps2.vhd"
set_module "de2_ps2"
set_module_description ""
set_module_property "className" "de2_ps2"
set_module_property "group" ""
set_module_property "libraries" [ list "ieee.std_logic_1164.all" "ieee.numeric_std.all" "std.standard.all" ]
set_module_property "synthesisFiles" "de2_ps2.vhd"

# Module parameters

# Interface clock
add_interface "clock" "clock" "sink" "asynchronous"
# Ports in interface clock
add_port_to_interface "clock" "avs_s1_clk" "clk"
add_port_to_interface "clock" "avs_s1_reset" "reset"

# Interface export_0
add_interface "export_0" "conduit" "start" "clock"
# Ports in interface export_0
add_port_to_interface "export_0" "PS2_Clk" "export"
add_port_to_interface "export_0" "PS2_Data" "export"

# Interface s1
add_interface "s1" "avalon" "slave" "clock"
set_interface_property "s1" "isNonVolatileStorage" "false"
set_interface_property "s1" "burstOnBurstBoundariesOnly" "false"
set_interface_property "s1" "readLatency" "0"
set_interface_property "s1" "holdTime" "0"
set_interface_property "s1" "printableDevice" "false"
set_interface_property "s1" "readWaitTime" "1"
set_interface_property "s1" "setupTime" "0"
set_interface_property "s1" "addressAlignment" "NATIVE"
set_interface_property "s1" "writeWaitTime" "0"
set_interface_property "s1" "timingUnits" "Cycles"
set_interface_property "s1" "minimumUninterruptedRunLength" "1"
set_interface_property "s1" "isMemoryDevice" "false"
set_interface_property "s1" "linewrapBursts" "false"
set_interface_property "s1" "maximumPendingReadTransactions" "0"
# Ports in interface s1
add_port_to_interface "s1" "avs_s1_address" "address"
add_port_to_interface "s1" "avs_s1_read" "read"
add_port_to_interface "s1" "avs_s1_chipselect" "chipselect"
add_port_to_interface "s1" "avs_s1_readdata" "readdata"
